name: Run tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:14-bullseye
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_DSN: postgres://postgres:postgres@postgres/postgres
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: pypy3.8-v7.3.9
      - name: Install poetry
        run: pip install poetry
      - name: Install dependancies
        run: poetry install
      - name: Lint
        run: |
          poetry run black --check .
          poetry run isort -c .
          poetry run mypy .
          poetry run flake8
      - name: Test
        run: poetry run pytest
